name: manage-azure-policy-aa40c40a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'enero18/initiatives/_Preview_Enable_Azure_Monitor_for_VMs_with_Azure_Monitoring_Agent(AMA)_9dffaf29-5905-4145-883c-957eb442c226/**'
#      - 'enero18/policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**'
#      - 'enero18/initiatives/TERRAFORM_SET_2_TAGS_0b001137e6604237a561cb0e/**'
#      - 'enero18/policies/Inherit_a_tag_from_the_resource_group_cd3aa116-8754-49c9-a813-ad46512ece54/**'
#      - .github/workflows/manage-azure-policy-aa40c40a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_aa40c40a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          enero18/initiatives/_Preview_Enable_Azure_Monitor_for_VMs_with_Azure_Monitoring_Agent(AMA)_9dffaf29-5905-4145-883c-957eb442c226/**
          enero18/policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**
          enero18/initiatives/TERRAFORM_SET_2_TAGS_0b001137e6604237a561cb0e/**
          enero18/policies/Inherit_a_tag_from_the_resource_group_cd3aa116-8754-49c9-a813-ad46512ece54/**
